version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: 'always'
    logging:
      driver: syslog
    ports:
      - 80:3002
    volumes:
      - ./:/var/www/meshireach
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: 'production'
