version: '3'
services:
  web:
    build: .
    ports:
      - 80:3002
    volumes:
      - ./:/var/www/meshireach
    stdin_open: true
    tty: true
    environment:
      HOST: 0.0.0.0
      PORT: 3002
