version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:8.16.0
    working_directory: ~/meshireach
jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          name: Save node modules cache
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: check format
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ${FINGER_PRINT}
      - run:
          name: Start ssh-keyscan
          command: ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
      - deploy:
          name: Start deploy
          command: sh ./deploy.sh

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: deploy
